### ISSUE TITLE
McCode MCPL_output should auto merge output files under MPI into a single file

### ISSUE THREAD

**Issue by tkittel** [mctools/mcpl#2]
This was discussed previously but postponed. It is not high urgency.

**Comment by willend** [comment]
This is done, here is a screenshot of the MCPL_output mcdoc page:

[McStas: MCPL_output Component.pdf](https://github.com/mctools/mcpl/files/741885/McStas.MCPL_output.Component.pdf)

**Comment by tkittel** [comment]
Great. I wonder why I never received a notification from github when you commented and closed on Jan 31...
