### ISSUE TITLE
should we provide ssw2mcpl and mcpl2ssw in mcstas?

### ISSUE THREAD

**Issue by tkittel** [mctools/mcpl#20]
Question for @willend and @ebknudsen : It seems that there is a lot of mcstas-mcnp work going on, so would it make sense to provide ssw2mcpl and mcpl2ssw for mcstas users, to make life more convenient for such users? (in the same way mcpltool is now available).

**Comment by willend** [comment]
Agreed, we should do this. I assume that this can be achieved by building the corresponding "fat" codes mentioned here: https://mctools.github.io/mcpl/hooks_mcnp/ ?

**Comment by tkittel** [comment]
That would be one way. Another way would be to compile sswread.c and sswmcpl.c from src/mcnp into a library (mcplssw.so) and use it to create the apps (similar to how mcpltool uses libmcpl.so).

Whatever is most convenient for you. The fat versions include zlib, so I guess you get more features that way.

**Comment by tkittel** [comment]
Once this is done, we should update the corresponding text on https://mctools.github.io/mcpl/hooks_mcnp (search for McStas) to say it is actually available (and from which release(s)).

**Comment by tkittel** [comment]
@willend / @ebknudsen : Is this still planned for next mcstas release? As you saw we got some poor windows users with mcstas struggling with the mcpl tar-ball just to get ssw2mcpl+mcpl2ssw, so might as well help them out.

**Comment by tkittel** [comment]
Lack of feedback so closing this issue - @willend @ebknudsen feel free to reopen if you want (also note the new phits2mcpl + mcpl2phits command which might be similarly interesting).

**Comment by willend** [comment]
Hi @tkittel and sorry for the lack of feedback! Including the saw tools was really easy and has been done already for a couple of releases. I will consider opening a McStas-ticket for the phits tools also.

**Comment by willend** [comment]
@tkittel this is now implemented on McCode master toward McStas 2.6. (And btw I added in pymcpltool as well)

**Comment by tkittel** [comment]
Great, thanks for letting me know :+1:
