### ISSUE TITLE
review mcxtrace docs

### ISSUE THREAD

**Issue by tkittel** [mctools/mcpl#24]
I now created the mcxtrace docs as well, and they of course also needs to be reviewed:

https://mctools.github.io/mcpl/hooks_mcxtrace/

Mostly I just based them on the mcstas docs.

A few differences and implied questions:

- I replaced mcdoc with mxdoc, hope this is correct.
- Version mentioned is 1.4 (what happened to 1.3 btw.)
- I could not link to MCPL_input and MCPL_output docs online, I guess they won't be available until version 1.4 of mcxtrace is actually released.
- I mention in the second paragraph that "spring 2017" is when 1.4 will be released. Correct?

**Comment by ebknudsen** [comment]
Looks good.
All of your bullet pts are correct. We decided to bump to 1.4 since it has been so long (far too long) in coming. 1.3 seemed bad luck in a sense...McXtrace 1.4 is due a couple of weeks after McStas 2.4

**Comment by tkittel** [comment]
Thanks!
