### ISSUE TITLE
McStas 2.4 + McXtrace 1.3 should contain mcpl.h and mcpl.c from release 1.0.0 or later.

### ISSUE THREAD

**Issue by tkittel** [mctools/mcpl#3]
A few improvements were added, we should make sure that next releases will have them in.

It won't be a total disaster if not, but we do want to move forward...

**Comment by tkittel** [comment]
And by mcpl.c I obviously meant mcpl_fat.c ...

**Comment by ebknudsen** [comment]
I knew that
/e

**Comment by willend** [comment]
Done (partially), files are in the repos for use with McStas:

<pre>
mcpl.h:#define MCPL_VERSION   10000 /* (10000*MAJOR+100*MINOR+PATCH)   */
</pre>

@ebknudsen some of my packaging-patches to mcstas-comps/ should be done for mcxtrace-comps/ also
