### ISSUE TITLE
mcpltool should be able to produce ascii output

### ISSUE THREAD

**Issue by tkittel** [mctools/mcpl#31]
It wouldn't be efficient, but some existing tools (see @willend's first comment in #9) support this format so might as well make sure such ascii output would be somewhat standard and correct. It is a relatively small change, especially if we don't try to include any meta-data in the format.

**Comment by willend** [comment]
I will probably make a dedicated mcstas instrument file for this, taking an MCPL file as input and defining a "free-form" Monitor_nD options string -> makes you able to generate McStas style histograms that can be plotted with our usual tools.

**Comment by tkittel** [comment]
Ok, I am not 100% sure I understand the details of what you want to do, but it sounds like a useful thing for mcstas users.

However, I'll probably add the option for ascii output to mcpltool in any case, given that the alternative is that people start (some did already) thinking they can use the normal mcpltool listings for such use (they have two problems: 1) reduced precision and 2) dynamic selection of columns to show).

**Comment by tkittel** [comment]
MCPL v1.2.0 was just released, adding a new "--text" option to the mcpltool (and pymcpltool).

So I will close this issue. Peter, I am assuming you will take care of documenting your new visualisation-with-mcstas feature somewhere, and at least add a link to it from https://mctools.github.io/mcpl/hooks_mcstas/ (+mcxtrace if appropriate).

**Comment by willend** [comment]
Sure. Will do.
