### ISSUE TITLE
_POSIX_C_SOURCE is defined to 1 - it should probably be 200809L

### ISSUE THREAD

**Issue by ebknudsen** [mctools/mcpl#33]
in mcpl.c _POSIX_C_SOURCE is defined to 1 - according to: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap02.html#tag_02_02_01 it should be 200809L

Furthermore - it is only defined if not defined before. In the case of the fat version of mcpl (i.e. with zlib included) it is defined earlier in the file (also to 1). 

This causes mcpl not to compile on FreeBSD as a side-effect of this is that fmax does not get declared.

Lastly _POSIX_C_SOURCE is never used for anything as far as I can tell.

**Comment by tkittel** [comment]
Thanks for the detailed report @ebknudsen. I'll get to this over the next few weeks and publish a new release (there are a few other items discovered in the python interface I want to deal with as well).

**Comment by ebknudsen** [comment]
Just to add a little thing (hopefully without also adding confusion) : It is likely wrt. the fat version of mcpl this is partially an upstream zlib issue. That's not to say it cannot be fixed in mcpl, though.

**Comment by tkittel** [comment]
Actually, I don't think it comes from zlib, so we should be able to completely fix this if your analysis is correct. Testing the fix now, will let you know when something appears on github for you to test.

**Comment by tkittel** [comment]
Hi @ebknudsen 

I have now tried to fix this and a few other minor issues. Can you try if the code at the HEAD of the develop branch works for you? Great if you can check both your FreeBSD but also your main platform(s):

https://github.com/mctools/mcpl/tree/develop

Assuming this all works, I will release MCPL v1.2.1 as soon as I get your feedback.

**Comment by ebknudsen** [comment]
ok - will try it out - stay tuned

**Comment by ebknudsen** [comment]
builds cleanly with both gcc and clang on FreeBSD 11

**Comment by ebknudsen** [comment]
builds cleanly with both gcc and clang on FreeBSD 11 / amd64 and FreeBSD 10 / i386

**Comment by tkittel** [comment]
Thanks a lot @ebknudsen !

Unfortunately, the actual release might be slightly delayed due to travis CI currently having issues with some of their queues - it would be nice to see all tests passing before actually performing a release. I assume this is fine with you, otherwise let met know.

**Comment by tkittel** [comment]
MCPL v1.2.1 was finally released, fixing this. Thanks a lot for the very useful report @ebknudsen
