### ISSUE TITLE
conversion error with MCNP6.2

### ISSUE THREAD

**Issue by gbrnfrdi** [mctools/mcpl#39]
Last time when I used the converters I used MCNP6.0 but since then I have switched to MCNP 6.2. My problem is that if I try to convert from a SSW file to MCPL file or just use the SSW file as a reference I always get an error:

ERROR: ssw_open_file error: File does not look like a supported MCNP SSW file

I assume that the version change could be the problem.

**Comment by gbrnfrdi** [comment]
test files here: https://github.com/gbrnfrdi/MCPL-conversion

**Comment by tkittel** [comment]
Thanks a lot for the report, we'll have a look and get back to you here :-)

**Comment by tkittel** [comment]
So I had a quick look with hexdump. It seems to me that the main thing changed is that the second fortran record in the file changed from 143 bytes to 191 bytes. If I quickly edit the code, changing 143 to 191, I am able to read your test file.

We have to wait for @EsbenKlinkby for some more detailed verification before we can release a proper fix, but for now it just might be that simply hacking sswread.c and changing 143 with 191 in lines 327-339 will give you a short term workable solution for mcnp6.2.

**Comment by EsbenKlinkby** [comment]
Hi,

I had a look, and can confirm that Thomas' quick fix indeed does solve the problem. From the test files above, I made SSWs using MCNP6 and MCNP6.2. The particles in the resulting mcpl files are identical.
I also converted back into SSW format, and read the files back into MCNP6 and MCNP6.2 respectively.
Both run smoothly based based on the SSW source. 
The results of the mesh tally which was in the input differ somewhat - but this is to be expected between versions.
As a final check I compared the source code that writes the ssw files between MCNP6 and MCNP6.2. There are numerous differences, but this one seems to be the origin:
<     character(len=8)   :: id
<     character(len=128) :: ha        ←
<     character(len=19)  :: hi
<     character(len=8)   :: hk
<     character(len=8)   :: hl
<     character(len=19)  :: hp
<     character(len=5)   :: hv
---
>     character(len=8)  :: id
>     character(len=80) :: ha
>     character(len=19) :: hi
>     character(len=8)  :: hk
>     character(len=8)  :: hl
>     character(len=19) :: hp
>     character(len=5)  :: hv

it increased size by 48 characters, which is consistent with Thomas' fix.

Don't ask me why it changed length...

**Comment by EsbenKlinkby** [comment]
for the record. I don't know what GitHub insists that the text is bold. Perhaps the 'diff' characters confuses.  sorry

**Comment by tkittel** [comment]
Perfect, thanks a lot for the thorough verification @EsbenKlinkby .

A guess could be that someone asked for more title characters to be stored.

So I'll modify the mcpl code to work with mcnp6.2 as well, and report back here.

**Comment by tkittel** [comment]
MCPL v1.2.3 was just released, fixing support for MCNP 6.2, hopefully making things work for you again @gbrnfrdi.

Cheers,
Thomas

**Comment by gbrnfrdi** [comment]
Thanks a lot. I have made the modifications you have mentioned and the conversion is now working :)
