### ISSUE TITLE
SSW load error

### ISSUE THREAD

**Issue by ysyeom** [mctools/mcpl#45]
I tried to convert a SSW file to a MCPL file by using "ssw2mcpl". However, I found an error message:   "ERROR: ssw_load error: unexpected ssb data length." How to fix this error? Thanks!

**Comment by tkittel** [comment]
Hi there,

It is hard to say without more information. What is the exact command you are trying to run? Can you provide a sample ssw file which doesnt work for you (preferably not too massive), some information about your MCNP version, and if possible a simple input deck.

Cheers,
Thomas

**Comment by ysyeom** [comment]
Hi, I send you the MCNP input deck and ssw file via a link below. I used version 6.1 of MCNP.  

https://www.dropbox.com/s/1nzv1v3z7ldfrt3/MCNP%20input%20file.zip?dl=0 

Thanks!

**Comment by tkittel** [comment]
Thanks for the files. I had a quick look. It seems that the files contains an unexpected fortran record at the end of the header section. A quick hack making the code skip past it makes MCPL load the file as it should (seemingly at least). I can of course make the code skip over such a record if there, since it has a length much longer that the records in the particle data section, although I would prefer to understand it's origin a bit better first. If for instance it might occasionally have the same length as the particle data, it would give problems. @EsbenKlinkby can you help me look into this?

**Comment by EsbenKlinkby** [comment]
Hi,
thanks for the input. 
I made two quick tests.
1) re-making SSW using
          Code Name & Version = MCNP6, 1.0
on the ESS cluster. In this case the conversion seems to work OK:
ssw_open_file: Opened file "wssg":
ssw_open_file:    File layout detected : MCNP6
ssw_open_file:    Code ID fields : "mcnp" / "6.mpi"
ssw_open_file:    Title field : "Ground surface contamination: Step 1 - 5.0E-02 MeV - Outer Portion"
ssw_open_file:    Source statistics (histories):     5000000
ssw_open_file:    Particles in file            :          62
ssw_open_file:    Number of surfaces           :           3
ssw_open_file:    Histories at surfaces        :          62
MCPL: Attempting to compress file output.mcpl with gzip
MCPL: Succesfully compressed file into output.mcpl.gz
Created output.mcpl.gz

2) converting directly the SSW from the dropbox
Here I get:
[klinkby@r1n2 ~]$ ess_mcnp_ssw2mcpl rssa_0_6_out
ssw_open_file: Opened file "rssa_0_6_out":
ssw_open_file:    File layout detected : MCNP6
ssw_open_file:    Code ID fields : "mcnp" / "6.mpi"
ssw_open_file:    Title field : "Ground surface contamination: Step 1 - 5.0E-02 MeV - Outer Portion"
ssw_open_file:    Source statistics (histories):  1539607552
ssw_open_file:    Particles in file            :      628624
ssw_open_file:    Number of surfaces           :           3
ssw_open_file:    Histories at surfaces        :      628624
ERROR: ssw_load error: unexpected ssb data length



Can it be that the extra header record is only there if you have high nps? I can try to submit a job to the cluster to get nps=1539607552. However, the cluster is busy. Likely it would be faster if you try with nps=5000000.

best,
Esben

**Comment by tkittel** [comment]
@EsbenKlinkby did you use MCPN 6.1 like the reporter? I am not sure exactly what it means when you write version 1.0 here? If not the same version, then I assume that is the cause of any differences.

**Comment by EsbenKlinkby** [comment]
hi @tkittel . Yes, I used MCNP6.1. However, there is also a release 6.1.1, which I don't have available. It's possible that the reporter used this
 @ysyeom can you send/upload the header part of the output to screen. Corresponding to:
          Code Name & Version = MCNP6, 1.0
  
     _/      _/        _/_/_/       _/      _/       _/_/_/         _/_/_/
    _/_/  _/_/      _/             _/_/    _/       _/    _/     _/       
   _/  _/  _/      _/             _/  _/  _/       _/_/_/       _/_/_/    
  _/      _/      _/             _/    _/_/       _/           _/    _/   
 _/      _/        _/_/_/       _/      _/       _/             _/_/      
  
  +---------------------------------------------------------------------+
  | Copyright 2008. Los Alamos National Security, LLC.  All rights      |
  | reserved.                                                           |
  |   This material was produced under U.S. Government contract         |
  | DE-AC52-06NA25396 for Los Alamos National Laboratory, which is      |
  | operated by Los Alamos National Security, LLC, for the U.S.         |
  | Department of Energy. The Government is granted for itself and      |
  | others acting on its behalf a paid-up, nonexclusive, irrevocable    |
  | worldwide license in this material to reproduce, prepare derivative |
  | works, and perform publicly and display publicly. Beginning five    |
  | (5) years after 2008, subject to additional five-year worldwide     |
  | renewals, the Government is granted for itself and others acting on |
  | its behalf a paid-up, nonexclusive, irrevocable worldwide license   |
  | in this material to reproduce, prepare derivative works, distribute |
  | copies to the public, perform publicly and display publicly, and to |
  | permit others to do so. NEITHER THE UNITED STATES NOR THE UNITED    |
  | STATES DEPARTMENT OF ENERGY, NOR LOS ALAMOS NATIONAL SECURITY, LLC, |
  | NOR ANY OF THEIR EMPLOYEES, MAKES ANY WARRANTY, EXPRESS OR IMPLIED, |
  | OR ASSUMES ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY,  |
  | COMPLETENESS, OR USEFULNESS OF ANY INFORMATION, APPARATUS, PRODUCT, |
  | OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE WOULD NOT INFRINGE |
  | PRIVATELY OWNED RIGHTS.                                             |
  +---------------------------------------------------------------------+
  
1mcnp     version 6.mpi ld=12/19/17  
 
thanks,

best,
Esben

**Comment by ysyeom** [comment]
Hi Keith, can you confirm the MCNP6 version used to generate the SSW file (rssa_0_6_out)?

Thanks!
Yeon Soo

___________________
Yeon Soo Yeom, Ph.D.
Postdoctoral Fellow, Radiation Epidemiology Branch,
Division of Cancer Epidemiology & Genetics,
National Cancer Institute, National Institutes of Health
9609 Medical Center Dr, Rockville, MD 20850
+1-240-276-5322 (office)
+1-301-910-1831 (cell)
Email: yeonsoo.yeom@nih.gov<mailto:yeonsoo.yeom@nih.gov>

**Comment by ysyeom** [comment]
Hi,

We used the MCNP6 Version 1.0. Please see the screen as well.

Thanks!

[Image]


[Image]


_____________________
Yeon Soo Yeom, Ph.D.
Postdoctoral Fellow,
REB/DCEG/NCI/NIH,
Email: yeonsoo.yeom@nih.gov

________________________________
From: Yeom, Yeon Soo (NIH/NCI) [F]
Sent: Thursday, April 25, 2019 10:31:49 AM
To: mctools/mcpl; mctools/mcpl; Griffin, Keith (NIH/NCI) [F]
Cc: Mention
Subject: RE: [mctools/mcpl] SSW load error (#45)

Hi Keith, can you confirm the MCNP6 version used to generate the SSW file (rssa_0_6_out)?

Thanks!
Yeon Soo

___________________
Yeon Soo Yeom, Ph.D.
Postdoctoral Fellow, Radiation Epidemiology Branch,
Division of Cancer Epidemiology & Genetics,
National Cancer Institute, National Institutes of Health
9609 Medical Center Dr, Rockville, MD 20850
+1-240-276-5322 (office)
+1-301-910-1831 (cell)
Email: yeonsoo.yeom@nih.gov<mailto:yeonsoo.yeom@nih.gov>

**Comment by tkittel** [comment]
@ysyeom, I think something went wrong with your screenshot. Does your log file say the same date as Esbens:

```
1mcnp version 6.mpi ld=12/19/17
```

**Comment by ysyeom** [comment]
You can see our code's data (12/18/15) is different from the date of Esbens (12/19/17), whlie both indicate the same version. Is it a big problem? Thanks!

_____________________
Yeon Soo Yeom, Ph.D.
Postdoctoral Fellow,
REB/DCEG/NCI/NIH,
Email: yeonsoo.yeom@nih.gov

**Comment by tkittel** [comment]
Hi @ysyeom. No, it is not a problem as such, but it would be nice to understand why Esben can't reproduce your issue.

As it is, I have an idea of which workaround to implement - but with more information it could become less hacky and less likely that the workaround will cause other unforeseen problems in the future.

**Comment by ysyeom** [comment]
Hi, Is there any update on this issue?

Thanks!
Yeon Soo

**Comment by tkittel** [comment]
So @EsbenKlinkby did some further investigations, but he can't really reproduce your issues with his version of MCNP. That makes it a bit difficult to fix in a manner which is 100% sure to not cause issues for other users. However, I will at least make some sort of workaround so it works for your specific file and then post an update here.

**Comment by ysyeom** [comment]
Thanks for your efforts! I really look forward to your update soon.

Best regards,
Yeon Soo

___________________
Yeon Soo Yeom, Ph.D.
Postdoctoral Fellow, Radiation Epidemiology Branch,
Division of Cancer Epidemiology & Genetics,
National Cancer Institute, National Institutes of Health
9609 Medical Center Dr, Rockville, MD 20850
+1-240-276-5322 (office)
+1-301-910-1831 (cell)
Email: yeonsoo.yeom@nih.gov<mailto:yeonsoo.yeom@nih.gov>

**Comment by tkittel** [comment]
The fix is a little bit more complicated than I thought, and I won't have time until next week to do it properly. However, as you seems to be in a hurry I created a quick hack version of ssw2mcpl for you which will probably work for your use-case in the short-term.

I put it at: http://tkittel.web.cern.ch/tkittel/ssw2mcpl_app_fat_quickfix.c

Example of how it can be downloaded, compiled and used to convert your file to MCPL (note the WARNING emitted):

```
(thki@detsim01 lala)> wget -q http://tkittel.web.cern.ch/tkittel/ssw2mcpl_app_fat_quickfix.c
(thki@detsim01 lala)> gcc -std=c99 -lm ssw2mcpl_app_fat_quickfix.c -o ssw2mcpl_quickfix
(thki@detsim01 lala)> ./ssw2mcpl_quickfix rssa_0_6_out 
ssw_open_file: Opened file "rssa_0_6_out":
ssw_open_file:    File layout detected : MCNP6
ssw_open_file:    Code ID fields : "mcnp" / "6.mpi"
ssw_open_file:    Title field : "Ground surface contamination: Step 1 - 5.0E-02 MeV - Outer Portion"
ssw_open_file:    Source statistics (histories):  1539607552
ssw_open_file:    Particles in file            :      628624
ssw_open_file:    Number of surfaces           :           3
ssw_open_file:    Histories at surfaces        :      628624
WARNING: Unexpected record length encountered. Will try to skip over it.
MCPL: Attempting to compress file output.mcpl with gzip
MCPL: Succesfully compressed file into output.mcpl.gz
Created output.mcpl.gz
```

**Comment by tkittel** [comment]
Hi @ysyeom . Did the quick fix work for you? Would be useful to verify that before I proceed with the real fix :-)

**Comment by ysyeom** [comment]
Hi @tkittel,

I am really sorry for the late reply. I have been so busy for a while due to my baby born. 

I just confirmed the fixed code works well for all SSW files in trouble with the original code. 

Thanks!
Yeon Soo

**Comment by tkittel** [comment]
Hi @ysyeom 

First of all big congratulations!! We are about to make a new MCPL release (1.3.0) within the next few days, but I will at the very least make sure that it includes a workaround for this issue.

Cheers,
Thomas

**Comment by tkittel** [comment]
MCPL 1.3.0 has been released, it should automatically support files like yours now. @ysyeom let me know if it works for you (when you have time).

Cheers,
Thomas
