### ISSUE TITLE
mcpl insatll

### ISSUE THREAD

**Issue by eddymaoui** [mctools/mcpl#52]
hi
how can i install mcpl in win 10 via cmake, knowing i will want to convert mcnp code to mcstas.
thanks

**Comment by willend** [comment]
Hi @eddymaoui,

The last few releases of McStas actually contains precompiled versions of the relevant MCPL tools, so this is what is generally recommended.

Also please note that no conversion of MCNP “code” is involved, and what MCPL can be used for is transfer of neutron events between the two (and other) codes.

**Comment by eddymaoui** [comment]
hi @willend 
yes, I know that there are MCPL tools like source for example (mcpl_input) embedded in mcstas.
I want to use the mcnp file as a source for a diffraction system in mcstas, like that
1) mcnp-->mcpl
2) mcpl-->mcstas
but I found the problem when installing mcpl in Windows 10. using the steps described in
*Building via CMake *

**Comment by willend** [comment]
As I remember (at least from McStas 2.5) the ssw2mcpl tool is included, which is all you need:

Simply include an SSW card in your MCNP deck and convert to MCPL via the ssw2mcpl included in your McStas installation.

**Comment by willend** [comment]
As can be seen in the below screenshot, ssw2mcpl is indeed included in McStas 2.5 on Windows. - And what it can do is as mentioned a conversion between MCNP "source surface" data and MCPL. 


<img width="761" alt="Screenshot 2019-09-28 at 22 51 13" src="https://user-images.githubusercontent.com/8593355/65822344-8a72a980-e242-11e9-9ed0-2cf4c74aded5.png">

**Comment by eddymaoui** [comment]
hi @willend 
i need an example of a mcnp file to test the ssw2mcpl tool.
thanks

**Comment by tkittel** [comment]
Hi @eddymaoui . To avoid any licensing concerns regarding MCNP, we in general refrain from providing users with such files in the scope of the MCPL project.

Also, wouldn't it be fair to say that if you can't produce your own MCNP output, then you won't really need ssw2mcpl :-)

**Comment by tkittel** [comment]
No more feedback, closing.
