### ISSUE TITLE
MCPL files are created outside the specified output directory in McStas 2.3

### ISSUE THREAD

**Issue by kalliopikanaki** [mctools/mcpl#7]
Hi, I am playing with McStas 2.3 on the DMSC cluster. I am sure you are aware that the MCPL output component does not create the MCPL file inside the output directory that the user specifies at launching. For now I am solving this by adding some unique configuration string parameters to the filename but I would prefer a solution that fully minimizes the risk of overwriting files. Most probably this is already taken care of but I am mentioning it just in case...

**Comment by ebknudsen** [comment]
This has been fixed in the McStas development tree
