### ISSUE TITLE
np.float and np.int expired in newer version of numpy. Conflicting mcpl.py

### ISSUE THREAD

**Issue by jorobledo** [mctools/mcpl#72]
Numpy deprecated `np.float` and `np.int` on [v1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated), and then expired the expressions on [v1.24.0](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations). Both of these expressions are used in [`mcpl.py`](https://github.com/mctools/mcpl/blob/master/src/python/mcpl.py), therefore newer versions of numpy raise error when using this script. Conda is currently packaging with [v1.24.3](https://anaconda.org/anaconda/numpy).

**Comment by tkittel** [comment]
Thanks @jorobledo ! So do you agree with my interpretation that the correct thing now is to simply use `float` and `int` rather than `np.float` and `np.int`?

**Comment by tkittel** [comment]
Actually, the notes you link to answer my question.

**Comment by jorobledo** [comment]
Yes. I forgot to put the answer, sorry about that. `float` and `int` are good enough, and the way to go!

**Comment by tkittel** [comment]
Thanks. FYI I will most likely look on providing a new MCPL release concerning this on Tuesday.

**Comment by tkittel** [comment]
I'll keep it open until I actually do the work ;-)

**Comment by tkittel** [comment]
Funny thing is, I now realise that @MilanKlausz fixed this 4 months ago in our dev repo, I just forgot to make a new release!

@MilanKlausz this is why we need a CI setup to keep pestering me in this case :smiling_face_with_tear:

**Comment by tkittel** [comment]
New release is out here on github, but my upload to PyPI is getting some gateway errors so the PyPI package is still not updated.

**Comment by tkittel** [comment]
Seems like pypi is under maintenance, I will try again later.

**Comment by tkittel** [comment]
Tada, the new release is now available on both conda-forge (full release) and pypi (Python API only):

- https://anaconda.org/conda-forge/mcpl/files?version=1.6.2
- https://pypi.org/project/mcpl/#history

Closing!
