### ISSUE TITLE
Need easy visualisation tools

### ISSUE THREAD

**Issue by tkittel** [mctools/mcpl#9]
ESS dgcode users have access to visualisation tools already, but outside users do not. Apparently some users in their desperation are making their own python-based parsing of mcpltool ascii output and subsequent plotting, to work around this.

We should provide something of a higher quality than this, but probably not the full power available in ESS dgcode (since it would require a looot of code to be exported). I am thinking the most portable solution would be a python-matplotlib based one (with which I am anyway familar). The question becomes if this python code would need a compiled mcpl library to work, or if we want to reimplement mcpl reading in python-only code (if the latter, we could make a single portable file for users to download and run).

**Comment by willend** [comment]
Would indeed be a great functionality addition! 

On the McStas / McXtrace side we support a really basic ascii column/matrix based plotting - maybe the "fat" mcpltool binary could be made to generate similar output files?

**Comment by tkittel** [comment]
Well, doesn't piping the output of the mcpltool cmd or the mcpl_dump function (with a flag to skip the header and -l0 to list all particles) to an ascii file already give you what you want? Or close enough that you could wrap it all in one of your little perl scripts and call it "mcstas_mcpl_plotter"? :-)

Of course, be aware that the columns printed are not always the same (i.e. no polarisation columns are printed when polarisation is disabled in the file), but the first line contains the column names.

**Comment by tkittel** [comment]
Issues #31 (ascii output) and #27 (python-only reader) were opened in response to the discussion above.

**Comment by tkittel** [comment]
Both issues #31 and #27 were solved by the MCPL release 1.2.0.

Furthermore, MCPL release 1.2.0 introduces easy visualisation (and more!) in the new pympcltool:

https://mctools.github.io/mcpl/usage_cmdline/#extract-statistics-from-a-file

Closing here.
